version: "3"
services:
  posts-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=testtest
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
