version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  posts-backend:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=testtest
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=testtest
